name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Rye
        run: |
          curl -sSf https://rye-up.com/get | bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Install dependencies
        run: rye sync

      - name: Start Docker services
        run: docker compose up -d

      - name: Run tests
        run: rye test -v

      - name: Stop Docker services
        run: docker compose down
        if: always()
